### ISSUE TITLE
Might want to add `pcall` to your lua `require`

### ISSUE THREAD

**Issue by ms-jpq** [adelarsq/vim-emoji-icon-theme#3]
right now if the `lua` imports fail (because the users have not installed say `lsp-status`), it kill the whole plugin.

Something like

```lua
local go, imported = pcall(require, "path")
if go then
   do something with imported
end
```

would solve this issue

**Comment by adelarsq** [comment]
@ms-jpq Thanks for the hint and sorry for the delay.
I didn't notice that since I'm already using the nightly NeoVim for some time 🙂
